### ISSUE TITLE
setAttribute

### ISSUE THREAD

**Issue by tomasc** [tomasc/dragonfly_svg#3]
- [x] add to README
- [x] refactor `setDimensions`, `setNamespace`, `setPreserveAspectRatio` and `setViewBox` to use `setAttribute`

**Comment by tomasc** [comment]
@tvdeyen this would be good to do if you're up for it

**Comment by tomasc** [comment]
I have updated the README

**Comment by tvdeyen** [comment]
My Open Source schedule is full, sorry ;)

https://github.com/tvdeyen/

But, yes this would be great.

**Comment by tomasc** [comment]
np, i just did it, it's simple enough

**Comment by tomasc** [comment]
solved by #6
